root: true
env:
  browser: true
  node: true
  es2021: true
  jest: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2021 # same as 12
  project: ./tsconfig.json # プロジェクト内の型認識に使用
  sourceType: module # use import/export
plugins:
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jest/recommended
  - prettier
